Intermediate dplyr
au-cru/site pull request #50
Opened 2020-01-06 13:12 UTC by SaraTomiolo

created a partial draft of the intermediate lesson

2020-01-06 17:27 UTC, lwjohnst86 requested changes
Thanks so much!! I'll look this over more later, but I have a few comments.

:grinning:

2020-01-06 17:27 UTC, lwjohnst86 commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +```{r}
```suggestion
```{r, eval=FALSE}
```

2020-01-06 17:27 UTC, lwjohnst86 commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +2. Learn to combine group_by() and summarize() function with pivot_longer() and pivot_wider() functions.
Put backticks around code in text. E.g.

    `group_by()`

2020-01-06 17:27 UTC, lwjohnst86 commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +
Add Johannes here.

2020-01-06 17:27 UTC, lwjohnst86 commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +View(population)
View should not be used within an R Markdown document.

2020-01-06 17:27 UTC, lwjohnst86 commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +### Pivot_wider()
A bit more descriptive header titles would make it easier to understand the content of the section.

2020-01-09 18:05 UTC, SaraTomiolo commented on content/material/2020-01-17-intermediate-dplyr.Rmd
> +
```suggestion
- Johannes Enevoldsen
```

2020-01-13 12:19 UTC, lwjohnst86 approved these changes
Thanks @SaraTomiolo. I'll merge this PR in and address more of the comments in @JohannesNE PR.

2020-01-13 12:19 UTC, merged